spring:
  web:
    resources:
      static-locations: file:static-content, classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
  datasource:
    url: jdbc:mysql://localhost:3306/testproj
    username: root
    password: password
  application:
    name: testproj-backend
  graphql:
    graphiql:
      enabled: true
  flyway:
    create-schemas: true
    schemas: testproj
    default-schema: testproj
    init-sqls: CREATE SCHEMA IF NOT EXISTS testproj;

server:
  port: 5000